env:
    - PROTOBUF_VERS="3.2.0"

language: rust
rust:
    - stable
    - beta
    - nightly

before_install:
    - ./install_protobuf.sh
    - export PATH=$(pwd)/bin:/home/travis/.cargo/bin:$PATH
    - protoc --version

script:
    - cargo build --all --verbose
    - cargo test --all --verbose
