[package]
name = "cross_communication"
version = "0.1.0"
authors = ["Dylan Maccora <maccora17@gmail.com>"]
# build = "gen_proto.sh" 

[dependencies]

[workspace]
members = [
  "chat-client",
  "chat-server"
]
